name: iosApp
options:
  bundleIdPrefix: io.flowdux.sample
  deploymentTarget:
    iOS: "15.0"

settings:
  DEVELOPMENT_TEAM: ""

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - iosApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: io.flowdux.sample.iosApp
      INFOPLIST_GENERATION_MODE: GeneratedFile
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: "5.0"
      FRAMEWORK_SEARCH_PATHS:
        - "$(inherited)"
        - "$(SRCROOT)/../shared/build/bin/iosSimulatorArm64/debugFramework"
        - "$(SRCROOT)/../shared/build/bin/iosArm64/releaseFramework"
    dependencies:
      - framework: "../shared/build/bin/iosSimulatorArm64/debugFramework/shared.framework"
        embed: true
